### ISSUE TITLE
[QUESTION]: Using different IDF with Sinergym

### ISSUE THREAD

**Issue by Jaydeemourg** [jajimer/sinergym#201]
### System Info

Describe the characteristic of your environment:
 * i installed sinergym  manually , setup the necessary setting and tested it with the try_env.py which worked successfully
 * Sinergym Version 1.8.1
 * OS: Ubuntu 18.04
 * Python version 3.9
 * Gym version 0.23.1

### Question ?
I want to create an environment with my particular building .idf file and weather data (.epw). I have placed both .idf and weather data files in the building and weather folder of sinergym.  the xml configuration file has also been created. 

upon executing the try_env.py, i got an error stating that "AttributeError: No table with reference 'Construction_InternalSource'".

while trying to debug the problem, i noticed that there exists this heading in my idf file.``` ===========  ALL OBJECTS IN CLASS: CONSTRUCTION:INTERNALSOURCE ===========```.  what could be the cause of the error?

```
!-   ===========  ALL OBJECTS IN CLASS: CONSTRUCTION:INTERNALSOURCE ===========

Construction:InternalSource,
    DE L KD,                 !- Name
    6,                       !- Source Present After Layer Number
    5,                       !- Temperature Calculation Requested After Layer Number
    1,                       !- Dimensions for the CTF Calculation
    0.09,                    !- Tube Spacing {m}
    0.0,                     !- Two-Dimensional Temperature Calculation Position {dimensionless}
    Parkett 13mm,            !- Outside Layer
    Estrich 35mm,            !- Layer 2
    Gipsfaserplatte 18mm,    !- Layer 3
    Luftraum ruhend WS auf 15-300mm,  !- Layer 4
    Beton 250mm,             !- Layer 5
    Luftraum ruhend WS auf 15-300mm,  !- Layer 6
    Stahlblech 5mm;          !- Layer 7

```

**Comment by AlejandroCN7** [comment]
Currently, we are not working on integrating new buildings into Sinergym (Pending for future versions), as it requires more factors than it seems, apparently.

First, you should set up a **variables.cfg** and **observations and actions space** that are valid for your building. Second, it is important that you set up in the IDF an **externalInterface** object so that you can control the correct schedules. Finally, you will have to deal with the **specifics of your IDF**.

For more information about configuration variables and action space and observations visit **our documentation**, for IDF manipulation I recommend you to visit the BCVTB and Energyplus documentation: [here](https://bigladdersoftware.com/epx/docs/8-0/input-output-reference/page-047.html)

Note: Please title the issue next time :)
Thank you!

**Comment by jajimer** [comment]
Hi @Jaydeemourg. Thanks for using Sinergym :)
Apparently it seems there is a problem with the IDF itself, as the reference 'Construction_InternalSource' is not found (possibly this is a just a typo). Take a look at [opyplus documentation](https://opyplus.readthedocs.io/en/v1.3.0/quickstart/index.html), as it allows you to simulate IDFs and it is great for debugging.
As @AlejandroCN7 mentioned, we are currently working on integrating new buildings and designing a standard way for adding them, so hopefully in a future release they might be controlled with Sinergym.

Regards!

**Comment by Jaydeemourg** [comment]
@AlejandroCN7 @jajimer thanks for your prompt response. I will work on regenerating an appropriate idf as you have mentioned. 
for your preview, here is [my particular idf file](https://github.com/Jaydeemourg/sinergym/blob/main/NEU_Simulation_Buero_Library_bcvtb.idf)
