### ISSUE TITLE
Weather files

### ISSUE THREAD

**Issue by jajimer** [jajimer/sinergym#5]
Include several weather files, so different combinations of building and climate can be simulated.

The main sources for these files are:
- DOE's 19 climate zones, most of them in USA ([Link](https://www.energycodes.gov/development/commercial/prototype_models))
- Climate.OneBuilding files, from most of the world ([Link](http://climate.onebuilding.org/default.html)).

When integrating these files, the design day must be also taken into account.

TO DOs:
- [x] Design days have to be included manually. Find a way to do it automatically
- [x] Modify weather from one year to another
- [ ] Include more types of weather files, and also more locations (not USA)

**Comment by biemann** [comment]
Hi, I have a question regarding the modification of weather files from one year to another. Did you mean here the option to use Ornstein-Uhlenbeck noise to avoid having the same weather for each episode? Or is it also possible to specify the weather files that are used in the simulation?

I have a list of weather files of consecutive years that I want to use in a specific order.

The change I would like to implement is relatively straightforward (and can solve it myself); one option would be to pass a list of weather files (instead of a single weather file) and then call each episode the next element of the list. By taking a look at the reset function, it seems that most of the necessary steps are already implemented there.

I am wondering whether this is interesting for you. This is a feature in Moriyama et al's environment that I find pretty nice. (They ask to define custom weather files via environment variables, which is potentially easier to deal with than defining them in the __init__ file)

But I really like this library so far!

**Comment by AlejandroCN7** [comment]
@biemann take a look in [our environments register](https://github.com/jajimer/sinergym/blob/main/sinergym/__init__.py), these environment specifications can be modified in this way:

`env=gym.make(<env_name>, weather_file=<new_weather_file>)`

Probably simulation won't be ok due to IDF is not modified in consequence.

**Comment by biemann** [comment]
> We have Ornstein-Uhlenbeck noise implemented in order to not use the same weather for each episode. The problem is when you change the weather file, since it is necessary to change IDF _DesignDay_ and _Location_ too. However, it is an interesting point of view. We will keep in mind for future updates! Thank you so much for support @biemann! 👍

Thanks for the answer. Yeah, I did not think of the design days 😕.  In the IDF files you just modify the values of the sizing period at the beginning?  Do you know where these changes are used in the simulation?

In general, when downloading EnergyPlus files from either source (the official website or ClimateOneBuilding), it comes with a .ddy file, containing the information required to change the design day. So I guess I could manually change this. I am wondering whether there is a way to automatically read these files in addition to the epw files when available.

**Comment by jajimer** [comment]
@biemann The sizing and design days are used in the warm-up and calibration of the simulation, before the episode begins.

I guess we could use the .ddy files to specify the design days. The changes we should implement then are:

- [ ] Add both .ddy and .epw files for each weather.
- [ ] Automatically read both of them for specifying Location and DesignDays in the IDF. You can use opyplus for reading .epw data from Python, hopefully it is similar for .ddy.
- [ ] Allow to pass both a string and a list in the weather_file parameter of the environment. If a list is passed, then each episode uses a different weather in order. Then during the initialization of the simulation, the IDF would be modified to work with the specified weather data.

Does this sound good to you? @AlejandroCN7 Maybe we could further think about the design days, but I think this is a good first approach.

Thanks for the comments and for using Sinergym! :)

**Comment by biemann** [comment]
This sounds good to me. I don't about opyplus, but it seems that the part we are interested in the .ddy files is the part following the text "Annual Heating 99.6%" for the winter design days, and "Annual Cooling (DB=>MWB)" for the summer design days.
Maybe we could use this to extract the relevant information from the files.

Such an approach may be prone to bugs however.

**Comment by AlejandroCN7** [comment]
I'm working on that. Probably during this week we will have some updates! ;)
